### ISSUE TITLE
Roadmap V0.0.1

### ISSUE THREAD

**Issue by elonehoo** [taruri-plugin-mips/.github#1]
- 增加所有架构的 dockerfile 「`高`\75%、[repository](https://github.com/taruri-plugin-mips/dockerfile)」
  - [x] mips
  - [ ] loong
    - qemu 无法完全模拟 Loong64 架构，需要探索交叉编译的可能性
  - [x] x86
  - [x] arm
  - ...
- 通用的打包脚本「`高`\100%」
  - [x] `install.sh` 可以在服务器中制作所有的 docker image
  - [x] `start.sh` 运行所有的 docker image
- 增加 管理项目，让我们可以在服务器中直接管理发版本的能力「`低`」
  - [ ] 可以通过 web 或者 [api](https://github.com/taruri-plugin-mips/bunded-server) 直接管理版本或者发版 80%
    - [x] [api](https://github.com/taruri-plugin-mips/bunded-server) 需要等待很长的时间，等待打包完成之后，将打包成功的多平台的压缩包，返回给发起方 
    - [x] 将 [bunded-server](https://github.com/taruri-plugin-mips/bunded-server) 从 [Nitor](https://nitro.build/) 直接迁移至 [Nuxt](https://nuxt.com/) [server](https://github.com/taruri-plugin-mips/server)
      - 界面设计应该设计在 [Figma](https://www.figma.com/) 上 [设计链接](https://www.figma.com/design/8D2bYVmtN5EfuwggizgBsm/tauri-release?node-id=0-1&t=XZBPONKP3sM9yxTp-1)
      - 需要修改 UX 体验，增强 log 的交互和渲染方式
      - 增加 build deb 的脚本
    - [x] 将 文件上传 到 服务器后，将其 解压缩后删除压缩包，启动 build.sh 等待 shell 的结束
    - [x] api 需要修改为 [SSE](https://h3.unjs.io/guide/websocket#server-sent-events-sse) 进行长链接
    - [x] 可以在上传之后选择是否全部打包、某个特殊版本的，还是打包成 debug 版本。
      - debug 模式不应该被记录在版本库中应该直接被删除或者载入 debug 库
      - 需要思考一下，后续应该有一个 `查看日志` 的功能，如何将查看日志的功能剥离出来
    - [x] 修改打包之后的文本符号
    - [x] 对于版本号管理
    - [ ] 在网页中直接下载压缩包
- 增加 基础的 bash 脚本，让发版可以最简单化「`高`\50%」
  - [x] 增加了整合文件的脚本
  - [ ] 将压缩包上传到接口的脚本
